import { Request, Response } from 'express';
import Exam from '../models/Exam';
import Question from '../models/Question';
import Submission from '../models/Submission';
import ActiveExamSession from '../models/ActiveExamSession';
import User from '../models/User';
import { config } from '../config';
import { GoogleGenAI } from '@google/genai';
// ========================
// DASHBOARD & PROFILE
// ========================
export const getDashboard = async (req: Request, res: Response) => {
  try {
    const studentId = req.user?.userId;
    const submissions = await Submission.find({ studentId }).populate('examId', 'title totalMarks passingMarks');

    const examsTaken = submissions.length;
    const passedExams = submissions.filter(s => s.isPassed).length;
    const failedExams = examsTaken - passedExams;

    let totalScore = 0;
    submissions.forEach(s => totalScore += s.score);
    const averageScore = examsTaken > 0 ? (totalScore / examsTaken) : 0;

    // Heatmap data could be generated by analyzing subject performance
    // For now we just return basic stats
    res.json({ examsTaken, passedExams, failedExams, averageScore, submissions });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
};

export const getTeachersDirectory = async (req: Request, res: Response) => {
  try {
    const teachers = await User.find({ role: 'teacher' }, 'name email phone profilePicture');
    res.json(teachers);
  } catch (error) {
    res.status(500).json({ message: 'Server error fetching teachers' });
  }
};

// ========================
// EXAM LOBBY
// ========================
export const getExamLobby = async (req: Request, res: Response) => {
  try {
    const now = new Date();

    // Categorize exams based on windowStart and windowEnd, AND student assignment
    const exams = await Exam.find({
      isActive: true,
      assignedStudents: req.user?.userId
    }).populate('subjectId', 'name');

    const active = exams.filter(e => e.windowStart <= now && e.windowEnd >= now);
    const upcoming = exams.filter(e => e.windowStart > now);
    const expired = exams.filter(e => e.windowEnd < now);

    res.json({ active, upcoming, expired });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
};

// ========================
// LIVE EXAM ENGINE
// ========================
export const startExam = async (req: Request, res: Response) => {
  try {
    const { examId } = req.params;
    const { identityPhoto } = req.body;
    const studentId = req.user?.userId;

    const exam = await Exam.findById(examId);
    if (!exam || !exam.isActive) return res.status(404).json({ message: 'Exam not available' });

    // Check if session already exists
    let session = await ActiveExamSession.findOne({ studentId, examId, status: 'in-progress' });

    let generatedQuestions: any[] = [];

    if (!session) {
      // Need to generate question pool
      if (exam.dynamicConfig?.enabled) {
        // Dynamic algorithm
        const easyQ = await Question.aggregate([{ $match: { subjectId: exam.subjectId, difficulty: 'Easy' } }, { $sample: { size: exam.dynamicConfig.easyCount } }]);
        const mediumQ = await Question.aggregate([{ $match: { subjectId: exam.subjectId, difficulty: 'Medium' } }, { $sample: { size: exam.dynamicConfig.mediumCount } }]);
        const hardQ = await Question.aggregate([{ $match: { subjectId: exam.subjectId, difficulty: 'Hard' } }, { $sample: { size: exam.dynamicConfig.hardCount } }]);

        generatedQuestions = [...easyQ, ...mediumQ, ...hardQ];
      } else {
        // Manual questions
        generatedQuestions = await Question.find({ _id: { $in: exam.manualQuestions } }).lean();
      }

      session = new ActiveExamSession({
        studentId,
        examId,
        status: 'in-progress',
        generatedQuestions: generatedQuestions.map(q => q._id),
        identityPhoto: identityPhoto || undefined
      });
      await session.save();
    } else {
      // Load existing questions for the session
      generatedQuestions = await Question.find({ _id: { $in: session.generatedQuestions } }).lean();
      if (identityPhoto && !session.identityPhoto) {
        session.identityPhoto = identityPhoto;
        await session.save();
      }
    }

    // STRIP correctOptionIndex and explanation for security
    const sanitizedQuestions = generatedQuestions.map((q: any) => {
      const { correctOptionIndex, explanation, ...safeQuestion } = q;
      return safeQuestion;
    });

    res.json({ session, exam, questions: sanitizedQuestions });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
};

export const syncSession = async (req: Request, res: Response) => {
  try {
    const { sessionId } = req.params;
    const { answers, visitedQuestions, flaggedQuestions, warnings } = req.body;

    const session = await ActiveExamSession.findById(sessionId);
    if (!session) return res.status(404).json({ message: 'Session not found' });

    // Ownership check — a student can only sync their own session
    if (session.studentId.toString() !== req.user?.userId) {
      return res.status(403).json({ message: 'Forbidden: This session does not belong to you' });
    }

    if (session.status !== 'in-progress') return res.status(400).json({ message: 'Session no longer active', status: session.status });

    // Atomic update
    await ActiveExamSession.updateOne(
      { _id: sessionId },
      {
        $set: { answers, flaggedQuestions, visitedQuestions, lastSyncTime: new Date() },
        $inc: { warnings: warnings || 0 }
      }
    );

    res.json({ message: 'Sync successful', status: session.status });
  } catch (error) {
    res.status(500).json({ message: 'Server error during sync' });
  }
};

export const submitExam = async (req: Request, res: Response) => {
  try {
    const { sessionId } = req.params;
    const studentId = req.user?.userId;

    const session = await ActiveExamSession.findById(sessionId);
    if (!session || session.status === 'submitted') return res.status(400).json({ message: 'Invalid session or already submitted' });

    // Ownership check — a student can only submit their own session
    if (session.studentId.toString() !== studentId) {
      return res.status(403).json({ message: 'Forbidden: This session does not belong to you' });
    }

    const exam = await Exam.findById(session.examId);
    if (!exam) return res.status(404).json({ message: 'Exam not found' });

    let score = 0;
    const questions = await Question.find({ _id: { $in: session.generatedQuestions } });
    const questionMap = new Map(questions.map(q => [q._id.toString(), q]));

    for (const answer of session.answers) {
      const q = questionMap.get(answer.questionId.toString());
      if (q && q.correctOptionIndex === answer.selectedOptionIndex) {
        score += q.marks;
      }
    }

    // If student received 3 or more warnings, they automatically fail the exam
    const isPassed = session.warnings >= 3 ? false : (score >= exam.passingMarks);

    const submission = new Submission({
      studentId,
      examId: exam._id,
      sessionId: session._id,
      answers: session.answers,
      score,
      isPassed,
      warnings: session.warnings,
      identityPhoto: session.identityPhoto
    });

    await submission.save();

    session.status = 'submitted';
    await session.save();

    res.status(201).json({ score, isPassed, totalMarks: exam.totalMarks });
  } catch (error) {
    res.status(500).json({ message: 'Server error during submission' });
  }
};

export const analyzeFrame = async (req: Request, res: Response) => {
  try {
    const { sessionId } = req.params;
    const { image } = req.body; // base64 string

    if (!image) {
      return res.status(400).json({ message: 'Image data is required' });
    }

    const session = await ActiveExamSession.findById(sessionId);
    if (!session || session.status !== 'in-progress') {
      return res.status(400).json({ message: 'Invalid or inactive session' });
    }

    if (session.studentId.toString() !== req.user?.userId) {
      return res.status(403).json({ message: 'Forbidden' });
    }

    // Process base64
    const base64Data = image.replace(/^data:image\/\w+;base64,/, "");

    // Save latest frame for live monitoring by teacher
    session.latestFrame = image;
    await session.save();

    if (!config.geminiApiKey) {
      return res.json({ violationDetected: false, reason: null });
    }

    const ai = new GoogleGenAI({ apiKey: config.geminiApiKey });
    const prompt = `Analyze this image from a student's webcam during an online exam. 
    Does the image contain any of the following cheating behaviors?
    - Multiple people in the frame
    - No person in the frame
    - Looking at a phone or another screen
    
    Answer strictly in this JSON format without markdown blocks:
    { "violationDetected": boolean, "reason": string | null }`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [
        prompt,
        { inlineData: { data: base64Data, mimeType: 'image/jpeg' } }
      ]
    });

    const aiText = response.text || '{}';
    const cleanedText = aiText.replace(/```json/g, '').replace(/```/g, '').trim();
    const analysis = JSON.parse(cleanedText);

    if (analysis.violationDetected) {
      session.warnings += 1;
      await session.save();
    }

    res.json(analysis);

  } catch (error) {
    console.error('Error analyzing frame:', error);
    res.status(500).json({ message: 'Server error analyzing frame' });
  }
};
